<div align="center">

**LAPORAN PRAKTIKUM**

**ALGORITMA DAN PEMROGRAMAN**

**“TIPE DATA DAN VARIABEL”**

**Disusun Oleh :**

**Ahmad Affandi**

**2611531015**

**Dosen Pengampu:**

**Wahyudi.DR.. S.T.M.T**

**Asisten Praktikum:**

**Riski Yuliandra**

<br>

 <img src="images/Logo_Unand.svg.webp" width="200">

<br>

**FAKULTAS TEKNOLOGI INFORMASI**

**DEPARTEMEN INFORMATIKA**

**UNIVERSITAS ANDALAS**

**2026**

</div>

<h1 align="center"><b>KATA PENGANTAR</h1></b>

Puji syukur penulis panjatkan kehadirat Tuhan Yang Maha Esa atas rahmat dan karunia-Nya, sehingga penulis dapat menyelesaikan laporan praktikum Algoritma dan Pemrograman Pertemuan Ke-2 yang mengangkat materi "Tipe Data dan Variabel" ini dengan baik.

Praktikum ini bertujuan untuk memberikan pemahaman mendalam mengenai konsep dasar variabel, penanganan tipe data standar Python (Numerik, String, dan Boolean), penerimaan masukan dinamis dari pengguna (*input*), pencetakan keluaran berformat (*output*), serta deklarasi nilai tetap (*konstanta*).

Penulis mengucapkan terima kasih kepada Bapak Wahyudi, S.T., M.T. selaku Dosen Pengampu serta Uda Riski Yuliandra selaku Asisten Praktikum atas bimbingan dan arahan yang telah diberikan. Penulis menyadari laporan ini masih memiliki kekurangan, sehingga kritik dan saran yang membangun sangat diharapkan demi perbaikan di masa mendatang.

<p align="right">Padang, 08 September 2026</p>

---
<b><h1 align=center>BAB I</h1></b>
<h1 align=center><b>PENDAHULUAN</h1></b>

## 1.1 Latar Belakang
Dalam penyusunan program komputer, variabel dan tipe data merupakan dua komponen dasar yang paling mendasar. Variabel berfungsi sebagai wadah untuk menyimpan data di dalam memori komputer, sedangkan tipe data menentukan jenis nilai yang dapat disimpan serta operasi aritmetika maupun logika apa saja yang dapat dilakukan terhadap data tersebut.

Bahasa pemrograman Python dikenal dengan sifatnya yang *dynamically typed*, artinya interpreter Python secara otomatis mendeteksi tipe data dari suatu variabel berdasarkan nilai yang dialokasikan tanpa perlu deklarasi tipe secara eksplisit. Meskipun demikian, seorang pemrogram harus memahami karakter dari masing-masing tipe data standar seperti tipe numerik (`int`, `float`, `complex`), tipe teks (`string`), dan tipe logika (`bool`). Selain itu, pemrosesan data interaktif memerlukan pemahaman mengenai fungsi masukan (`input()`), konversi tipe data (*type casting*), serta penggunaan konstanta untuk nilai yang bernilai tetap.

## 1.2 Tujuan
1. Memahami konsep deklarasi variabel dan mekanisme pengenalan tipe data bawaan pada Python.
2. Memahami karakteristik dan perbedaan tipe data numerik (`int`, `float`, `complex`), string (`string`), dan boolean (`bool`).
3. Mampu mengimplementasikan fungsi `input()` dan melakukan konversi tipe data (*type casting*) untuk pemrosesan aritmetika.
4. Memahami penerapan variabel bernilai tetap (*konstanta*) menggunakan penanda `Final` dari modul `typing` serta format pencetakan string (`string formatting`).

## 1.3 Manfaat
1. Mahasiswa mampu mengidentifikasi dan memilih tipe data yang tepat sesuai dengan kebutuhan kasus alur logika program.
2. Mahasiswa mampu membangun program interaktif yang dapat menerima masukan pengguna dan menghasilkan keluaran berformat.
3. Mahasiswa memiliki landasan yang kuat dalam mengelola variabel dan tipe data untuk tingkat alur pemrograman yang lebih kompleks.

---
<b><h1 align="center">BAB II</h1></b>
<h1 align=center><b>PEMBAHASAN</h1></b>

## 2.1 Dasar Teori
Konsep-konsep utama mengenai tipe data dan variabel pada bahasa Python meliputi:

1. **Variabel dan Dynamically Typed**: Variabel adalah pemetaan nama yang menunjuk ke lokasi memori penampung nilai. Dalam Python, variabel tidak perlu dideklarasikan tipe datanya terlebih dahulu. Interpreter akan mengevaluasi tipe data secara otomatis saat alokasi nilai dilakukan.
2. **Tipe Data Numerik**: Python mendukung tiga jenis numerik utama:
    - **Integer (`int`)**: Bilangan bulat positif atau negatif tanpa koma desimal.
    - **Float (`float`)**: Bilangan riil berpresisi presisi ganda yang mengandung titik desimal.
    - **Complex (`complex`)**: Bilangan kompleks berbentuk $a + bj$, di mana $a$ adalah bagian riil dan $b$ adalah bagian imajiner.
3. **Tipe Data String (`string`)**: Kumpulan karakter yang dibatasi oleh tanda petik tunggal (`'`), tanda petik ganda (`\"`), atau *triple quotes* (`\"\"\"` / `'''`). Tanda petik tiga memungkinkan penulisan teks multi-baris (*multiline string*) yang mempertahankan format spasi dan baris baru.
4. **Tipe Data Boolean (`bool`)**: Tipe data logika yang hanya memiliki dua kemungkinan nilai, yaitu `True` atau `False`. Nilai boolean sering kali dihasilkan dari evaluasi ekspresi kondisi atau operator perbandingan (misalnya `>=`, `<=`, `==`).
5. **Input dan Type Casting**: Fungsi `input()` digunakan untuk mengambil masukan dari pengguna secara interaktif melalui konsol. Karena keluaran bawaan fungsi `input()` selalu berbentuk String (`string`), maka diperlukan *type casting* menggunakan fungsi seperti `int()` atau `float()` agar nilai tersebut dapat dioperasikan secara matematis.
6. **Konstanta dan String Formatting**: Menurut standar konvensi PEP 8, konstanta dinyatakan dengan nama variabel berhuruf kapital. Dalam Python modern, kejelasan konstanta dipertegas dengan penanda `Final` dari modul `typing`. Untuk menampilkan nilai numerik atau konstanta secara rapi, digunakan *string formatting* (seperti operator `%` atau `%f` / `%.2f`).

## 2.2 Kode Program

### 2.2.1 Program "numerik1_2611531015.py"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [1]:
#create a variable with integer value.
a_1015=100
print("The type of variable having value", a_1015, "is ", type(a_1015))

#create a variable with float value.
b_1015=10.2345
print("The type of variable having value", b_1015, "is ", type(b_1015))

#crate a variable with complex value.
c_1015=100+3j
print("The type of variable having value", c_1015, "is ", type (c_1015))

The type of variable having value 100 is  <class 'int'>
The type of variable having value 10.2345 is  <class 'float'>
The type of variable having value (100+3j) is  <class 'complex'>


**Penjelasan :**
1. **Deklarasi Variabel Numerik**: Variabel `a_1015` diisi nilai `100` (bilangan bulat), `b_1015` diisi nilai `10.2345` (bilangan desimal), dan `c_1015` diisi nilai `100+3j` (bilangan kompleks dengan komponen imajiner `3j`).
2. **Fungsi `type()`**: Fungsi bawaan `type()` dipanggil untuk mendeteksi tipe kelas dari masing-masing variabel secara otomatis saat runtime.
3. **Pencetakan Output**: Fungsi `print()` menampilkan nilai variabel beserta kelas tipe datanya, yaitu masing-masing `<class 'int'>`, `<class 'float'>`, dan `<class 'complex'>`.

### 2.2.2 Program "string1_2611531015.py"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [3]:
nama_1015 = "Ahmad Affandi"
jenis_kelamin_1015 = 'L'
alamat_1015 = """
    Lubuk Gading VI
    Kec. Koto Tangah
    Kota Padang
"""
agama_1015 = 'Islam'
print("Nama saya adalah: ", nama_1015)
print("Jenis kelamin saya adalah: ", jenis_kelamin_1015)
print("Alamat saya adalah: ", alamat_1015)
print("Agama saya adalah: ", agama_1015)


Nama saya adalah:  Ahmad Affandi
Jenis kelamin saya adalah:  L
Alamat saya adalah:  
    Lubuk Gading VI
    Kec. Koto Tangah
    Kota Padang

Agama saya adalah:  Islam


**Penjelasan :**
1. **Variabel String Biasa**: Variabel `nama_1015`, `jenis_kelamin_1015`, dan `agama_1015` menyimpan teks dengan mengapit nilai menggunakan tanda petik tunggal (`'`) atau ganda (`\"`).
2. **Multiline String (`\"\"\"`)**: Variabel `alamat_1015` dibuat menggunakan *triple quotes* (`\"\"\"`). Pendekatan ini memungkinkan penulisan teks multi-baris sehingga alinea dan indentasi alamat tersimpan secara utuh tanpa perlu menuliskan karakter *escape* `\\n` secara manual.
3. **Hasil Keluaran**: Fungsi `print()` menampilkan seluruh informasi biodata tersebut secara runtut ke layar konsol.

### 2.2.3 Program "boolean1_2611531015.py"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [4]:
is_lulus_1015 = True
is_cumlaude_1015 = False

# Menggunakan Boolean
nilai_1015 = 85
batas_lulus_1015 = 75

# Menentukan nilai Boolean dari kondisi
status_kelulusan_1015 = nilai_1015 >= batas_lulus_1015

print("=== Check Kelulusan ===")
print("Nilai: ", nilai_1015)
print("Apakah lulus?: ", status_kelulusan_1015)


=== Check Kelulusan ===
Nilai:  85
Apakah lulus?:  True


**Penjelasan :**
1. **Inisialisasi Nilai Boolean**: Variabel `is_lulus_1015` dan `is_cumlaude_1015` secara eksplisit diberi nilai boolean `True` dan `False`.
2. **Evaluasi Operator Perbandingan**: Variabel `status_kelulusan_1015` menyimpan hasil evaluasi dari operator perbandingan `nilai_1015 >= batas_lulus_1015`. Karena `85 >= 75` bernilai benar, maka ekspresi ini menghasilkan nilai `True`.
3. **Output**: Konsol menampilkan status kelulusan berupa nilai Boolean `True` secara langsung.

### 2.2.4 Program "Input_2611531015.py"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [6]:
# Buat file dengan nama Input_NIM.py
# buat program untuk menghitung luas persegi panjang
# Nama variabel ditambvahb4 digit ni terakhir contoh: panjang_1234
# Program ini menggunakan fungsi input() untuk meminta pengguna
# memasukkan nilai panjang dan lebar persegi panjang
# Nilai yang dimasukkan akan dikonversi menjadi tipe data integer

panjang_1015 = input('Masukkan nilai panjang: ')
lebar_1015 = input('Masukkan nilai lebar: ')
luas_1015 = int(panjang_1015) * int(lebar_1015)
print("Luas = ", luas_1015)

Luas =  144


**Penjelasan :**
1. **Fungsi `input()`**: Mengambil masukan nilai panjang dan lebar dari pengguna. Secara default, hasil kembalian dari fungsi `input()` selalu bertipe data String (`string`).
2. **Type Casting (`int()`)**: Teks angka masukan dikonversi terlebih dahulu menjadi integer menggunakan `int(panjang_1015)` dan `int(lebar_1015)`. Konversi ini wajib dilakukan agar operator perkalian (`*`) melakukan operasi aritmetika matematika, bukan pengulangan string
3. **Perhitungan**: Variabel `luas_1015` menyimpan hasil perkalian panjang dan lebar lalu mencetak hasilnya ke layar konsol.

### 2.2.5 Program "Konstanta_2611531015.py"
Jalankan sel kode di bawah ini agar Jupyter otomatis menyimpan kodenya beserta outputnya sebagai satu kesatuan (tidak perlu screenshot terpisah untuk hasil run).

In [7]:
# Buat file dengan nama Konstanta_NIM.py
# Program ini menggunakan konstanta untuk menghitung luas lingkaran
# Nama variabel ditambah 4 digit nim terakhir contoh jari_1234

from typing import Final
PI: Final = 3.14
print("pi: %f" %(PI))
jari_1015 = float(input('Masukkan nilai jari-jari: '))
luas_1015 = PI * jari_1015 * jari_1015
print("luas lingkaran dengan jari-jari %.2f adalah %.2f" % (jari_1015, luas_1015))

pi: 3.140000
luas lingkaran dengan jari-jari 21.00 adalah 1384.74


**Penjelasan :**
1. **Deklarasi Konstanta `Final`**: Mengimpor modul `Final` dari paket `typing`. Penulisan `PI: Final = 3.14` menegaskan secara eksplisit bahwa variabel `PI` diniatkan sebagai nilai konstanta yang konstan/tetap.
2. **Casting `float()`**: Nilai masukan dari `input()` dikonversi menjadi tipe data desimal (`float`) agar pengguna dapat memasukkan nilai jari-jari pecahan.
3. **Format Pencetakan String (`%`)**: Penulisan `%f` mencetak nilai float standar, sedangkan penulisan `%.2f` digunakan untuk membatasi tampilan nilai desimal tepat dua angka di belakang koma pada keluaran konsol.

---
<h1 align=center><b>BAB III</b></h1>
<h1 align=center><b>KESIMPULAN</b></h1>

Berdasarkan praktikum mengenai **Tipe Data dan Variabel** yang telah dilakukan, dapat ditarik beberapa kesimpulan sebagai berikut:

1. Python mengelola variabel secara dinamis (*dynamically typed*), di mana tipe data dari suatu variabel secara otomatis dikenali oleh interpreter berdasarkan nilai yang diberikan saat runtime.
2. Setiap tipe data memiliki karakteristik dan kegunaan tersendiri: tipe numerik (`int`, `float`, `complex`) untuk pemrosesan angka, tipe `str` untuk manipulasi teks, serta tipe `bool` untuk logika perbandingan.
3. Fungsi `input()` selalu mengembalikan nilai bertipe String, sehingga proses konversi tipe data (*type casting*) seperti `int()` atau `float()` mutlak diperlukan sebelum melakukan operasi aritmetika.
4. Penggunaan modul `typing.Final` dan konvensi penulisan nama variabel kapital membantu menegaskan konstanta, serta pemformatan string (seperti `%.2f`) mempermudah penyajian angka desimal agar lebih rapi.

---
<h1 align=center><b>DAFTAR PUSTAKA</b></h1>

[1] C. Severance, *Python for Everybody: Exploring Data Using Python 3*. Ann Arbor, MI: Charles Severance, 2016. [Online]. Tersedia: https://www.py4e.com/book

[2] Python Software Foundation, \"Built-in Types - Python 3 Documentation,\" 2024. [Online]. Tersedia: https://docs.python.org/3/library/stdtypes.html

[3] S. Chacon dan B. Straub, *Pro Git*, edisi ke-2. New York, NY: Apress, 2014. [Online]. Tersedia: https://git-scm.com/book/en/v2

[4] Microsoft, \"Getting Started with Python in VS Code,\" Visual Studio Code Documentation, 2024. [Online]. Tersedia: https://code.visualstudio.com/docs/python/python-tutorial [Diakses tanggal: 08 September 2026].